<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Service.Empresa.Infrastructure\Service.Empresa.Infrastructure.csproj" />
    <ProjectReference Include="..\Service.Empresa.Application\Service.Empresa.Application.csproj" />
  </ItemGroup>

</Project>